---

- name: Playbook for role testing
  hosts: etcd
  roles:
    - config_template
    - role: "{{ playbook_dir | dirname | dirname | basename }}"

- name: Attempt a partial deployment of the role only
  hosts: etcd[0]
  roles:
    - config_template
    - role: "{{ playbook_dir | dirname | dirname | basename }}"

- name: Deploy the etcd3 gRPC gateways
  hosts: etcd_gateway
  roles:
    - config_template
    - role: "{{ playbook_dir | dirname | dirname | basename }}"

- name: Verify the role functions
  hosts: all
  tasks:
    - name: Check etcd is running
      command: pgrep -a etcd
      register: etcd_proc
      changed_when: false
    - name: Test etcd cluster health
      uri:
        url: "{{ etcd_url_scheme }}://127.0.0.1:{{ etcd_client_port }}/health"
        return_content: true
      register: etcd_health
      changed_when: false
    - name: Check role functions
      assert:
        that:
          - "'true' in etcd_health.content"
      changed_when: false
